//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace EFGetStarted.AspNetCore.NewDbPost.Recursos {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "15.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class Recurso {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Recurso() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("EFGetStarted.AspNetCore.NewDbPost.Recursos.Recurso", typeof(Recurso).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to acerca.
        /// </summary>
        public static string About {
            get {
                return ResourceManager.GetString("About", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Nombre.
        /// </summary>
        public static string Company_nombre_mostrar {
            get {
                return ResourceManager.GetString("Company_nombre_mostrar", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to SSN Compañia.
        /// </summary>
        public static string Company_SSN_mostrar {
            get {
                return ResourceManager.GetString("Company_SSN_mostrar", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tipo.
        /// </summary>
        public static string Company_type_mostrar {
            get {
                return ResourceManager.GetString("Company_type_mostrar", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Pago Anual.
        /// </summary>
        public static string Local_AnnualPayment {
            get {
                return ResourceManager.GetString("Local_AnnualPayment", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Nombre Negocio.
        /// </summary>
        public static string Local_BussinesName {
            get {
                return ResourceManager.GetString("Local_BussinesName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Fecha Termina.
        /// </summary>
        public static string Local_ContractEnd {
            get {
                return ResourceManager.GetString("Local_ContractEnd", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Fecha comienza.
        /// </summary>
        public static string Local_ContractStart {
            get {
                return ResourceManager.GetString("Local_ContractStart", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Deposito.
        /// </summary>
        public static string Local_Deposit {
            get {
                return ResourceManager.GetString("Local_Deposit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ID Spacio.
        /// </summary>
        public static string Local_ID_mostrar {
            get {
                return ResourceManager.GetString("Local_ID_mostrar", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Pago Mensual.
        /// </summary>
        public static string Local_MonthlyPayment {
            get {
                return ResourceManager.GetString("Local_MonthlyPayment", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Nombre Dueño.
        /// </summary>
        public static string Local_NameOwner {
            get {
                return ResourceManager.GetString("Local_NameOwner", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Precio x Pies.
        /// </summary>
        public static string Local_PriceSF {
            get {
                return ResourceManager.GetString("Local_PriceSF", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Pies Cuadrado.
        /// </summary>
        public static string Local_SquareFoot {
            get {
                return ResourceManager.GetString("Local_SquareFoot", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to El campo {0} es obligatorio.
        /// </summary>
        public static string Message_Error_Required {
            get {
                return ResourceManager.GetString("Message_Error_Required", resourceCulture);
            }
        }
    }
}
